import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the contact slice
const initialState = {
    name: null,
    email: null,
    message: null
};

// Create the contact slice
const contactSlice = createSlice({
    name: "contact",
    initialState,
    reducers: {
        // Define a reducer to set the contact form data
        setContactData: (state, action) => {
            state.name = action.payload.name;
            state.email = action.payload.email;
            state.message = action.payload.message;
        },
        // Define a reducer to clear the contact form data
        clearContactData: (state) => {
            state.name = null;
            state.email = null;
            state.message = null;
        }
    }
});

// Export the actions generated by the contact slice
export const { setContactData, clearContactData } = contactSlice.actions;

// Export the contact reducer
export default contactSlice.reducer;
